"""Add must_change_password to User

Revision ID: e2292f460e52
Revises: efedde8c87b2
Create Date: 2026-03-29 12:24:53.716897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2292f460e52'
down_revision: Union[str, Sequence[str], None] = 'efedde8c87b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE users SET must_change_password = False")
    
    # Make it non-nullable
    op.alter_column('users', 'must_change_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    # ### end Alembic commands ###
