"""
User Self-Service Endpoints — /api/v1/users

Endpoints that let the currently authenticated user view and manage
their own data. These are NOT admin-only — any logged-in user can
access their own data here.

Routes:
  Profile:
    GET   /me                              → Get your own profile.
    PATCH /me                              → Update your own name.

  Notifications:
    GET   /me/notifications                → List your notifications.
    PATCH /me/notifications/{id}/read      → Mark one notification as read.
    POST  /me/notifications/read-all       → Mark all notifications as read.
    DELETE /me/notifications/{id}          → Delete a notification.

  Activity Log:
    GET   /me/activity                     → View your own login and action history.
"""

from typing import List, Optional
import uuid
from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, update
from sqlalchemy.orm import joinedload

from app.db.base import get_db
from app.api.deps import get_current_user
from app.models.base_models import User, Notification, AuditLog
from app.models.enums import ActionType
from app.schemas.users import UserProfile, UserProfileUpdate
from app.schemas.notification import Notification as NotificationSchema
from app.schemas.audit import AuditLog as AuditLogSchema

router = APIRouter()


# ---------------------------------------------------------------------------
# Profile
# ---------------------------------------------------------------------------

@router.get(
    "/me",
    response_model=UserProfile,
    status_code=status.HTTP_200_OK,
    summary="Get the current user's profile",
    description=(
        "Returns the full profile of the currently authenticated user, including "
        "their name, email, role, active status, and last login timestamp. "
        "Useful for populating a 'My Account' or dashboard page on the frontend. "
        "This endpoint does not expose sensitive data such as password hashes."
    ),
)
async def get_my_profile(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(User).options(joinedload(User.role)).where(User.id == current_user.id)
    )
    user = result.scalars().first()
    if not user:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")
    return user


@router.patch(
    "/me",
    response_model=UserProfile,
    status_code=status.HTTP_200_OK,
    summary="Update the current user's profile",
    description=(
        "Allows the authenticated user to update their own `first_name` and/or `last_name`. "
        "Only the fields provided in the request body will be changed (partial update). "
        "Users cannot change their own email, role, or password through this endpoint — "
        "email/role changes require admin action via `PATCH /admin/users/{user_id}`, "
        "and password changes go through `POST /auth/change-password`."
    ),
)
async def update_my_profile(
    body: UserProfileUpdate,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(User).options(joinedload(User.role)).where(User.id == current_user.id)
    )
    user = result.scalars().first()
    if not user:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found")

    if body.first_name is not None:
        user.first_name = body.first_name
    if body.last_name is not None:
        user.last_name = body.last_name

    db.add(user)
    await db.commit()
    await db.refresh(user)

    # Re-fetch with role relationship populated
    result = await db.execute(
        select(User).options(joinedload(User.role)).where(User.id == user.id)
    )
    return result.scalars().first()


# ---------------------------------------------------------------------------
# Notifications
# ---------------------------------------------------------------------------

@router.get(
    "/me/notifications",
    response_model=List[NotificationSchema],
    status_code=status.HTTP_200_OK,
    summary="List the current user's notifications",
    description=(
        "Returns all notifications belonging to the authenticated user, ordered "
        "by most recent first. Use the optional `unread_only` query parameter to "
        "filter to only unread notifications. Notifications are generated by the "
        "system for events such as VM expiry warnings, VM deletions, and account "
        "suspension alerts."
    ),
)
async def list_my_notifications(
    unread_only: bool = Query(
        False,
        description="If true, returns only notifications that have not been marked as read."
    ),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    query = (
        select(Notification)
        .where(Notification.user_id == current_user.id)
        .order_by(Notification.sent_at.desc())
    )
    if unread_only:
        query = query.where(Notification.is_read == False)

    result = await db.execute(query)
    return result.scalars().all()


@router.patch(
    "/me/notifications/{notification_id}/read",
    response_model=NotificationSchema,
    status_code=status.HTTP_200_OK,
    summary="Mark a single notification as read",
    description=(
        "Marks the specified notification as read (`is_read = true`). "
        "Returns the updated notification object. "
        "Returns `404` if the notification does not exist or does not belong "
        "to the current user."
    ),
)
async def mark_notification_read(
    notification_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Notification).where(
            Notification.id == notification_id,
            Notification.user_id == current_user.id,
        )
    )
    notification = result.scalars().first()
    if not notification:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Notification not found",
        )

    notification.is_read = True
    db.add(notification)
    await db.commit()
    await db.refresh(notification)
    return notification


@router.post(
    "/me/notifications/read-all",
    status_code=status.HTTP_200_OK,
    summary="Mark all notifications as read",
    description=(
        "Bulk-marks every unread notification for the current user as read. "
        "Useful for a 'Mark all as read' button in a notification inbox UI. "
        "Returns the count of notifications that were updated."
    ),
)
async def mark_all_notifications_read(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Notification).where(
            Notification.user_id == current_user.id,
            Notification.is_read == False,
        )
    )
    unread = result.scalars().all()
    count = len(unread)

    for notification in unread:
        notification.is_read = True
        db.add(notification)

    await db.commit()
    return {"message": f"{count} notification(s) marked as read", "updated_count": count}


@router.delete(
    "/me/notifications/{notification_id}",
    status_code=status.HTTP_200_OK,
    summary="Delete a notification",
    description=(
        "Permanently deletes the specified notification. "
        "Returns `404` if the notification does not exist or does not belong "
        "to the current user. Useful for cleaning up dismissed alerts."
    ),
)
async def delete_notification(
    notification_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    result = await db.execute(
        select(Notification).where(
            Notification.id == notification_id,
            Notification.user_id == current_user.id,
        )
    )
    notification = result.scalars().first()
    if not notification:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Notification not found",
        )

    await db.delete(notification)
    await db.commit()
    return {"message": "Notification deleted"}


# ---------------------------------------------------------------------------
# Activity Log
# ---------------------------------------------------------------------------

@router.get(
    "/me/activity",
    response_model=List[AuditLogSchema],
    status_code=status.HTTP_200_OK,
    summary="View the current user's activity history",
    description=(
        "Returns the audit log entries that belong to the currently authenticated user, "
        "ordered by most recent first. This includes login attempts (successful and failed), "
        "logouts, password changes, and any VM actions the user has performed. "
        "Use the optional `action_type` query param to filter by a specific action. "
        "Use `limit` to control how many records are returned (default 50, max 200)."
    ),
)
async def get_my_activity(
    action_type: Optional[ActionType] = Query(
        None,
        description="Filter by a specific action type (e.g. login, logout, vm_create)."
    ),
    limit: int = Query(
        50,
        ge=1,
        le=200,
        description="Maximum number of records to return. Default is 50."
    ),
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    query = (
        select(AuditLog)
        .where(AuditLog.user_id == current_user.id)
        .order_by(AuditLog.occurred_at.desc())
        .limit(limit)
    )
    if action_type:
        query = query.where(AuditLog.action_type == action_type)

    result = await db.execute(query)
    return result.scalars().all()
